runtime:
  cat: /bin/cat
  g++: /usr/bin/g++
  g++11: /usr/bin/g++-5
  g++14: /usr/bin/g++-5
  gcc: /usr/bin/gcc
  java8: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
  javac8: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
  perl: /usr/bin/perl
  python: /usr/bin/python2.7
  python3: /usr/bin/python3.5
